version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/docker-image"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker-image"
    schedule:
      interval: "daily"
