name: Rebuild Master

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_TOKEN }}
          registry: ghcr.io
      - name: Cache Docker layers
        uses: actions/cache@v2.1.4
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Run Buildx
        run: |
          if [ ${{ matrix.node_version }} -eq "14" ]; then
              export DEVEL="-t ctmagazin/ctnodered:devel -t ghcr.io/ct-open-source/ctnodered:devel"
          fi
          export PLATFORMS="linux/amd64,linux/arm/v7,linux/arm64/v8,linux/arm/v6"
          docker buildx build \
            --platform $PLATFORMS \
            -o type=registry \
            -t ctmagazin/ctnodered:"devel-${{ matrix.node_version }}" \
            -t ghcr.io/ct-open-source/ctnodered:"devel-${{ matrix.node_version }}" \
            $DEVEL \
            --build-arg NODE_VERSION=${{ matrix.node_version }} \
            --build-arg NODE_RED_VERSION=latest \
            --build-arg OS=alpine \
            --build-arg BUILD_DATE="$(date +"%Y-%m-%dT%H:%M:%SZ")" \
            --build-arg TAG_SUFFIX=devel-${{ matrix.node_version }} \
            --file ./docker-image/Dockerfile ./docker-image
