name: Code check with Trivy
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  build:
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/ctmagazin/ctnodered:${{ github.sha }} --file ./docker-image/Dockerfile ./docker-image

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/ctmagazin/ctnodered:${{ github.sha }}' 
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
